# -*- coding: utf-8 -*-
{
    "name": "Clinica - Sistema de Gestion Hospitalaria (HMS)",
    "summary": "Sistema completo de gestion clinica con citas, evaluaciones, prescripciones, tratamientos y procedimientos",
    "description": "",
    "version": "19.0.1.0.1",
    "category": "Medical",
    "author": "tagre.pe",
    "maintainer": "cvjuan270@gmail.com",
    "website": "https://tagre.pe",
    "license": "Other proprietary",
    "depends": ["tgr_hms_base", "web_timer_widget", "website", "digest"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "report/patient_cardreport.xml",
        "report/report_medical_advice.xml",
        "report/report_prescription.xml",
        "report/appointment_report.xml",
        "report/evaluation_report.xml",
        "report/treatment_report.xml",
        "report/procedure_report.xml",
        "report/medicines_label_report.xml",
        "data/sequence.xml",
        "data/mail_template.xml",
        "data/hms_data.xml",
        "data/digest_data.xml",
        "wizard/cancel_reason_view.xml",
        "wizard/pain_level_view.xml",
        "wizard/reschedule_appointments_view.xml",
        "views/hms_base_views.xml",
        "views/patient_view.xml",
        "views/physician_view.xml",
        "views/evaluation_view.xml",
        "views/appointment_view.xml",
        "views/diseases_view.xml",
        "views/medicament_view.xml",
        "views/prescription_view.xml",
        "views/medication_view.xml",
        "views/treatment_view.xml",
        "views/procedure_view.xml",
        "views/resource_cal.xml",
        "views/medical_alert.xml",
        "views/account_view.xml",
        "views/product_kit_view.xml",
        "views/template.xml",
        "views/res_config_settings_views.xml",
        "views/digest_view.xml",
        "views/res_users.xml",
        "views/menu_item.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "tgr_hms/static/src/js/hms_graph_field.js",
            "tgr_hms/static/src/js/hms_graph_field.xml",
            "tgr_hms/static/src/js/hms_graph_field.scss",
            "tgr_hms/static/src/scss/custom.scss",
        ]
    },
    "demo": [
        # "demo/doctor_demo.xml",
        # "demo/patient_demo.xml",
        # "demo/appointment_demo.xml",
        # "demo/medicament_demo.xml",
    ],
    "images": [],
    "installable": True,
    "application": True,
    "sequence": 1,
}
