# -*- coding: utf-8 -*-
{
    "name": "Gestion de Radiologia",
    "summary": "Sistema de gestion de radiologia con solicitudes, pruebas, resultados y portal de pacientes",
    "version": "19.0.1.0.3",
    "category": "Medical",
    "author": "tagre.pe",
    "maintainer": "cvjuan270@gmail.com",
    "website": "https://tagre.pe",
    "license": "Other proprietary",
    "depends": ["tgr_hms_base", "tgr_hms_documents_preview"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "report/radiology_prescription.xml",
        "report/radiology_report.xml",
        "report/radiology_request_results.xml",
        "data/mail_template.xml",
        "data/data.xml",
        "data/digest_data.xml",
        "views/radiology_request_view.xml",
        "views/radiology_test_view.xml",
        "views/radiology_patient_test_view.xml",
        "views/hms_base_view.xml",
        "views/res_config.xml",
        "views/portal_template.xml",
        "views/templates_view.xml",
        "views/radiology_view.xml",
        "views/digest_view.xml",
        "views/menu_item.xml",
    ],
    "demo": [
        "data/radiology_demo.xml",
    ],
    "images": [],
    "installable": True,
    "application": True,
    "sequence": 1,
}
