# -*- coding: utf-8 -*-
{
    "name": "Hospitalizacion y Gestion de Camas - HMS",
    "summary": "Gestion de hospitalizaciones, camas, pabellones, edificios y registros de defuncion",
    "category": "Medical",
    "description": "",
    "version": "19.0.1.0.1",
    "author": "tagre.pe",
    "maintainer": "cvjuan270@gmail.com",
    "website": "https://tagre.pe",
    "license": "Other proprietary",
    "depends": ["tgr_hms", "tgr_hms_surgery"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "wizard/transfer_accommodation_view.xml",
        "views/hospitalization_view.xml",
        "views/hospitalization_care_views.xml",
        "views/bed_view.xml",
        "views/ward_view.xml",
        "views/building_view.xml",
        "views/ot_view.xml",
        "views/hms_base_view.xml",
        "views/death_register.xml",
        "views/care_plan_template_view.xml",
        "views/res_config_settings_views.xml",
        "views/digest_view.xml",
        "report/report_hospital_discharge.xml",
        "report/report_visiting_pass.xml",
        "report/report_hospitalization_patient_card.xml",
        "report/ward_patient_list_report.xml",
        "report/report_hospitalization_forecast.xml",
        "data/sequence.xml",
        "data/hms_data.xml",
        "data/digest_data.xml",
        "views/menu_item.xml",
        "wizard/tgr_hospitalization_forecast_view.xml",
    ],
    "sequence": 1,
    "application": True,
}
