# -*- coding: utf-8 -*-
{
    "name": "Gestion de Laboratorio",
    "summary": "Sistema completo de gestion de laboratorio clinico con pruebas, muestras, perfiles y resultados",
    "description": "",
    "version": "19.0.1.0.1",
    "category": "Medical",
    "author": "tagre.pe",
    "maintainer": "cvjuan270@gmail.com",
    "website": "https://tagre.pe",
    "license": "Other proprietary",
    "depends": ["base", "product", "tgr_hms_base", "portal"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "report/lab_samples_report.xml",
        "report/paper_format.xml",
        # data
        # "data/mail_template.xml",
        "data/laboratory_data.xml",
        "data/digest_data.xml",
        "data/lab_area.xml",
        "data/product.category.csv",
        "data/product.product.csv",
        "data/tgr.lab.test.uom.csv",
        "data/tgr.laboratory.sample.type.csv",
        "data/tgr_lab_test.xml",
        "data/lab_test_critearea.xml",
        "data/tgr.laboratory.test.profile.xml",
        "data/tgr_laboratory_test_profile_line.xml",
        # end data
        "views/lab_uom_view.xml",
        "views/laboratory_request_view.xml",
        "views/laboratory_view.xml",
        "views/laboratory_test_view.xml",
        "views/laboratory_patient_test_view.xml",
        "views/laboratory_sample_view.xml",
        "views/hms_base_view.xml",
        "views/res_config.xml",
        "views/portal_template.xml",
        "views/templates_view.xml",
        "views/digest_view.xml",
        "views/laboratory_area_views.xml",
        "views/laboratory_profile_views.xml",
        "views/report_templates.xml",
        "views/report_lab_prescription.xml",
        "views/report_lab_results.xml",
        "views/menu_item.xml",
    ],
    "demo": [
        # "data/laboratory_demo.xml",
    ],
    "images": [
        "static/description/hms_laboratory_almightycs_cover.jpg",
    ],
    "installable": True,
    "application": True,
    "sequence": 1,
}
