# -*- coding: utf-8 -*-
{
    "name": "Cirugia Medica",
    "summary": "Gestion de cirugias, plantillas quirurgicas y paquetes de cirugia",
    "category": "Medical",
    "version": "19.0.1.0.4",
    "author": "tagre.pe",
    "maintainer": "cvjuan270@gmail.com",
    "website": "https://tagre.pe",
    "license": "Other proprietary",
    "depends": ["tgr_hms"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/data.xml",
        "data/digest_data.xml",
        "report/package_report.xml",
        "report/surgery_report.xml",
        "views/surgery_base.xml",
        "views/surgery_template_view.xml",
        "views/surgery_view.xml",
        "views/hms_base_view.xml",
        "views/package_view.xml",
        "views/res_config_settings_views.xml",
        "views/digest_view.xml",
        "views/menu_item.xml",
    ],
    "demo": [
        "demo/hms_demo.xml",
    ],
    "images": [],
    "sequence": 1,
    "application": True,
}
